cardInfo.DrawCard(x, y)
draw_set_halign(fa_left)
draw_set_color(c_white)
draw_text(x+100, y-15, "ID: " + string(id))
draw_text(x+100, y, "Below: " + string(cardBelow))
draw_text(x+100, y+15, "Above: " + string(cardAbove))